# Generated by Django 2.0.3 on 2018-12-22 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20181216_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='queuepartnerbenefitspage',
            name='order',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='queueuserbenefitspage',
            name='order',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
